package compactencoding

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// compat_test.go replays wire vectors produced by the JavaScript
// compact-encoding library (see testdata/gen-vectors.js). Every vector is
// checked in both directions: the Go encoder must produce the exact bytes the
// JS encoder produced, and the Go decoder must read those bytes back to the
// same value.

type vector struct {
	Codec string          `json:"codec"`
	Value json.RawMessage `json:"value"`
	Hex   string          `json:"hex"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()
	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var file struct {
		Version string   `json:"version"`
		Vectors []vector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &file); err != nil {
		t.Fatal(err)
	}
	t.Logf("vectors generated by compact-encoding@%s", file.Version)
	return file.Vectors
}

func checkVector[T any](t *testing.T, enc Encoder[T], v vector, value T) {
	t.Helper()
	want, err := hex.DecodeString(v.Hex)
	if err != nil {
		t.Fatal(err)
	}

	got, err := Encode(enc, value)
	if err != nil {
		t.Fatalf("%s %s: encode: %v", v.Codec, v.Value, err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("%s %s: encode = %x, JS = %x", v.Codec, v.Value, got, want)
	}

	decoded, err := Decode(enc, want)
	if err != nil {
		t.Fatalf("%s %s: decode: %v", v.Codec, v.Value, err)
	}
	if !reflect.DeepEqual(decoded, value) {
		t.Errorf("%s %s: decode = %v, want %v", v.Codec, v.Value, decoded, value)
	}
}

func checkJSON[T any](t *testing.T, enc Encoder[T], v vector) {
	t.Helper()
	var value T
	if err := json.Unmarshal(v.Value, &value); err != nil {
		t.Fatalf("%s: %v", v.Codec, err)
	}
	checkVector(t, enc, v, value)
}

func checkHexBytes(t *testing.T, enc Encoder[[]byte], v vector) {
	t.Helper()
	var s string
	if err := json.Unmarshal(v.Value, &s); err != nil {
		t.Fatal(err)
	}
	value, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	checkVector(t, enc, v, value)
}

type compatMessage struct {
	Name   string
	Age    uint
	Admin  bool
	Data   []byte
	Scores []int
	ID     uint64
}

func TestJSVectors(t *testing.T) {
	seen := map[string]int{}
	for _, v := range loadVectors(t) {
		seen[v.Codec]++
		switch v.Codec {
		case "uint":
			checkJSON(t, NewUint(), v)
		case "int":
			checkJSON(t, NewInt(), v)
		case "uint8":
			checkJSON(t, NewUint8(), v)
		case "uint16":
			checkJSON(t, NewUint16(), v)
		case "uint32":
			checkJSON(t, NewUint32(), v)
		case "uint64":
			checkJSON(t, NewUint64(), v)
		case "int8":
			checkJSON(t, NewInt8(), v)
		case "int16":
			checkJSON(t, NewInt16(), v)
		case "int32":
			checkJSON(t, NewInt32(), v)
		case "int64":
			checkJSON(t, NewInt64(), v)
		case "string":
			checkJSON(t, NewString(), v)
		case "bool":
			checkJSON(t, NewBool(), v)
		case "buffer":
			checkHexBytes(t, NewBuffer(), v)
		case "array:uint":
			checkJSON(t, NewArray(NewUint()), v)
		case "array:int":
			checkJSON(t, NewArray(NewInt()), v)
		case "array:string":
			checkJSON(t, NewArray(NewString()), v)
		case "array:bool":
			checkJSON(t, NewArray(NewBool()), v)
		case "array:array:uint":
			checkJSON(t, NewArray(NewArray(NewUint())), v)
		case "struct":
			want, _ := hex.DecodeString(v.Hex)
			msg := compatMessage{
				Name:   "pear",
				Age:    42,
				Admin:  true,
				Data:   []byte{0xde, 0xad, 0xbe, 0xef},
				Scores: []int{1, -2, 3},
				ID:     0x0102030405060708,
			}
			got, err := Marshal(msg)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(got, want) {
				t.Errorf("struct: Marshal = %x, JS = %x", got, want)
			}
			var decoded compatMessage
			if err := Unmarshal(want, &decoded); err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(decoded, msg) {
				t.Errorf("struct: Unmarshal = %+v, want %+v", decoded, msg)
			}
		default:
			t.Errorf("no Go codec for vector %q", v.Codec)
		}
	}
	for codec, n := range seen {
		t.Logf("%-18s %d vectors", codec, n)
	}
}

// The JS decoder refuses arrays with more than 0x100000 elements before
// allocating; the Go decoder must do the same rather than trusting the length.
func TestArrayTooBig(t *testing.T) {
	_, err := Decode(NewArray(NewUint()), []byte{0xfe, 0x01, 0x00, 0x10, 0x00})
	if err == nil {
		t.Fatal("expected error")
	}
	if _, ok := err.(*EncodingErrorArrayTooBig); !ok {
		t.Fatalf("expected EncodingErrorArrayTooBig, got %T %v", err, err)
	}
	if _, err := Decode(NewArray(NewUint8()), append([]byte{0xfe, 0x00, 0x00, 0x10, 0x00}, make([]byte, 0x100000)...)); err != nil {
		t.Fatalf("0x100000 elements should decode: %v", err)
	}
}

// Truncated input must surface as an error, never as an index panic.
func TestTruncatedInput(t *testing.T) {
	expectFail := func(name string, in []byte, err error) {
		t.Helper()
		if err == nil {
			t.Errorf("%s: decode(%x) should fail", name, in)
		} else if _, ok := err.(*EncodingErrorOutOfBounds); !ok {
			t.Errorf("%s: decode(%x) = %T, want EncodingErrorOutOfBounds", name, in, err)
		}
	}
	for n := 0; n < 8; n++ {
		in := make([]byte, n)
		if n < 1 {
			_, err := Decode(NewUint8(), in)
			expectFail("uint8", in, err)
		}
		if n < 2 {
			_, err := Decode(NewUint16(), in)
			expectFail("uint16", in, err)
		}
		if n < 4 {
			_, err := Decode(NewUint32(), in)
			expectFail("uint32", in, err)
		}
		_, err := Decode(NewUint64(), in)
		expectFail("uint64", in, err)
	}
	for _, in := range [][]byte{
		{},
		{0xfd, 0x01},
		{0xfe, 0x01, 0x02, 0x03},
		{0xff, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07},
	} {
		_, err := Decode(NewUint(), in)
		expectFail("uint", in, err)
	}
	for _, in := range [][]byte{
		{},
		{0x05, 0x01},
		{0xfd, 0xff, 0xff, 0x01},
		{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}, // length whose addition to Start would wrap around
	} {
		_, err := Decode(NewString(), in)
		expectFail("string", in, err)
		_, err = Decode(NewBuffer(), in)
		expectFail("buffer", in, err)
		_, err = Decode(NewArray(NewUint8()), in)
		if err == nil {
			t.Errorf("array: decode(%x) should fail", in)
		}
	}

	state := &State{End: 1, Buffer: make([]byte, 1)}
	if err := NewUint16().Encode(state, 1); err == nil {
		t.Error("uint16 encode into a 1-byte buffer should fail")
	}
}
